# Generated by Django 6.0.7 on 2026-09-04 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(db_index=True, help_text='Unique subject code (e.g., MATH101, ENGL101)', max_length=20, unique=True)),
                ('subject_name', models.CharField(db_index=True, help_text='Full name of the subject', max_length=200)),
                ('subject_description', models.TextField(blank=True, help_text='Brief description of the subject', null=True)),
                ('units', models.DecimalField(decimal_places=1, default=3.0, help_text='Number of units', max_digits=4)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subject is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['subject_code'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_description', models.TextField(help_text='Detailed course description')),
                ('course_objectives', models.TextField(help_text='Learning objectives and outcomes')),
                ('course_outcomes', models.TextField(help_text='Expected course outcomes')),
                ('grading_system', models.TextField(help_text='Grading system and breakdown')),
                ('required_textbooks', models.TextField(blank=True, help_text='Required textbooks and references', null=True)),
                ('recommended_readings', models.TextField(blank=True, help_text='Recommended readings and resources', null=True)),
                ('attendance_policy', models.TextField(blank=True, help_text='Attendance policy', null=True)),
                ('grading_policy', models.TextField(blank=True, help_text='Grading policy and requirements', null=True)),
                ('classroom_policies', models.TextField(blank=True, help_text='Classroom policies and expectations', null=True)),
                ('consultation_hours', models.CharField(blank=True, help_text='Instructor consultation hours', max_length=200, null=True)),
                ('instructor_name', models.CharField(blank=True, help_text='Name of the instructor', max_length=200, null=True)),
                ('instructor_email', models.EmailField(blank=True, help_text='Instructor email address', max_length=254, null=True)),
                ('instructor_contact', models.CharField(blank=True, help_text='Instructor contact number', max_length=20, null=True)),
                ('school_year', models.CharField(help_text='School year (e.g., 2024-2025)', max_length=20)),
                ('semester', models.CharField(help_text='Semester (e.g., 1st Semester, 2nd Semester)', max_length=20)),
                ('is_published', models.BooleanField(default=False, help_text='Whether the syllabus is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(help_text='The subject this syllabus belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Syllabus',
                'verbose_name_plural': 'Syllabi',
                'db_table': 'syllabi',
                'ordering': ['subject__subject_code'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.IntegerField(help_text='Module number (e.g., 1, 2, 3...)')),
                ('module_title', models.CharField(help_text='Title of the module', max_length=200)),
                ('module_type', models.CharField(choices=[('Lecture', 'Lecture'), ('Laboratory', 'Laboratory'), ('Discussion', 'Discussion'), ('Recitation', 'Recitation'), ('Assignment', 'Assignment'), ('Exam', 'Exam'), ('Quiz', 'Quiz'), ('Project', 'Project'), ('Activity', 'Activity'), ('Presentation', 'Presentation')], default='Lecture', help_text='Type of module', max_length=20)),
                ('week_number', models.IntegerField(help_text='Week number')),
                ('week_title', models.CharField(blank=True, help_text='Title of the week/lesson', max_length=200, null=True)),
                ('topics', models.TextField(help_text='Topics covered in this module')),
                ('learning_objectives', models.TextField(help_text='Learning objectives for this module')),
                ('learning_outcomes', models.TextField(help_text='Expected learning outcomes')),
                ('activities', models.TextField(blank=True, help_text='Activities and exercises', null=True)),
                ('assignments', models.TextField(blank=True, help_text='Assignments and tasks', null=True)),
                ('assessments', models.TextField(blank=True, help_text='Assessment methods', null=True)),
                ('resources', models.TextField(blank=True, help_text='Resources and materials needed', null=True)),
                ('references', models.TextField(blank=True, help_text='References and readings', null=True)),
                ('duration', models.CharField(blank=True, help_text='Duration (e.g., 1 week, 2 weeks)', max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Start date of the module', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date of the module', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the module has been completed')),
                ('is_published', models.BooleanField(default=False, help_text='Whether the module is published')),
                ('order', models.IntegerField(default=0, help_text='Order of modules for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('syllabus', models.ForeignKey(help_text='The syllabus this module belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academic.syllabus')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'modules',
                'ordering': ['syllabus', 'module_number', 'order'],
                'unique_together': {('syllabus', 'module_number')},
            },
        ),
    ]
