# Generated by Django 6.0.7 on 2026-09-04 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['syllabus', 'module_number', 'order'], 'verbose_name': 'Module', 'verbose_name_plural': 'C. Modules'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_code'], 'verbose_name': 'Subject', 'verbose_name_plural': 'A. Subjects'},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['subject__subject_code'], 'verbose_name': 'Syllabus', 'verbose_name_plural': 'B.  Syllabus'},
        ),
        migrations.CreateModel(
            name='ModuleLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField(help_text='Lesson number within the module (e.g., 1, 2, 3...)')),
                ('lesson_title', models.CharField(help_text='Title of the lesson', max_length=200)),
                ('lesson_type', models.CharField(choices=[('Introduction', 'Introduction'), ('Lecture', 'Lecture'), ('Discussion', 'Discussion'), ('Demonstration', 'Demonstration'), ('Practical', 'Practical'), ('Activity', 'Activity'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment'), ('Review', 'Review'), ('Exam', 'Exam'), ('Laboratory', 'Laboratory'), ('Presentation', 'Presentation'), ('Recitation', 'Recitation'), ('Group Work', 'Group Work'), ('Research', 'Research'), ('Field Work', 'Field Work')], default='Lecture', help_text='Type of lesson', max_length=20)),
                ('lesson_description', models.TextField(blank=True, help_text='Brief description of the lesson', null=True)),
                ('lesson_objectives', models.TextField(help_text='Learning objectives for this lesson')),
                ('lesson_content', models.TextField(help_text='Main content of the lesson')),
                ('key_points', models.TextField(blank=True, help_text='Key points to remember', null=True)),
                ('discussion_questions', models.TextField(blank=True, help_text='Discussion questions for the lesson', null=True)),
                ('activities', models.TextField(blank=True, help_text='Activities and exercises', null=True)),
                ('assignments', models.TextField(blank=True, help_text='Assignments and tasks', null=True)),
                ('resources', models.TextField(blank=True, help_text='Resources and materials needed', null=True)),
                ('references', models.TextField(blank=True, help_text='References and readings', null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order of lessons within the module')),
                ('is_published', models.BooleanField(default=False, help_text='Whether the lesson is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(help_text='The module this lesson belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academic.module')),
            ],
            options={
                'verbose_name': 'Module Lesson',
                'verbose_name_plural': 'Module Lessons',
                'db_table': 'module_lessons',
                'ordering': ['module', 'lesson_number', 'order'],
                'unique_together': {('module', 'lesson_number')},
            },
        ),
    ]
