# Generated by Django 6.0.7 on 2026-09-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_module_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleLesson',
        ),
    ]
