# Generated by Django 6.0.7 on 2026-09-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_delete_modulelesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='lessons',
            field=models.TextField(blank=True, help_text='Lessons and Discussions', null=True),
        ),
    ]
