"""
Django settings for moist_drf project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^hl2!1)mh=u)=pc2uv1d^&2#au2fpz%+$d7%#3rj4xpiut#a#@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.library',
    'apps.academic',

]
# Jazzmin Settings
JAZZMIN_SETTINGS = {
    # Title of the admin (will be displayed on the login screen and admin header)
    "site_title": "MOIST LMS Admin",
    
    # Title on the brand (will be displayed on the admin header)
    "site_header": "MOIST LMS",
    
    # Logo to use for your site, must be present in static files (default: False)
    "site_logo": "admin/img/moist1.png",
    
    # Logo to use for your site in the login form (default: False)
    "login_logo": "admin/img/moist1.png",
    
    # Logo to use for your site in the login form (default: False)
    "login_logo_dark": "admin/img/moist1.png",
    
    # CSS classes that are applied to the logo (default: None)
    "site_logo_classes": "img-circle",
    
    # Relative path to a favicon for your site (default: False)
    "site_icon": "admin/img/favicon.ico",
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to MOIST LMS",
    
    # Copyright on the footer
    "copyright": "MOIST LMS © 2024",
    
    
    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["library", "academic", "auth"],
    
    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "library": [{
            "name": "Make Reports",
            "url": "make_reports",
            "icon": "fas fa-chart-pie",
            "permissions": ["library.view_librarycatalog"]
        }]
    },
    
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'moist_drf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'moist_drf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cover images path (optional - if you want separate URL)
COVER_IMAGES_URL = '/media/covers/'  # This is just a subpath of MEDIA_URL
COVER_IMAGES_ROOT = os.path.join(MEDIA_ROOT, 'covers')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'